# Config for running the EvalRecipe in eval_mteb.py to evaluate embedding model on MTEB
#
# TODO(pls331): support tune download
#
# To launch, run the following command:
#    tune run dev/eval_mteb --config llama3_2_embedding\eval_mteb_sentence_transformer

# Model arguments
model:
  _component_: sentence_transformers.SentenceTransformer
  model_name_or_path: intfloat/multilingual-e5-large
  device: cuda
  prompts:
    ##
    # task_name : "Prompt for the task"
    # To be compatible with MTEB, task_name must be one of those 
    # defined in mteb.abstasks.TaskMetadata.TASK_TYPE
    ##
    Classification: "Classify the following text: "
    Retrieval: "Retrieve semantically similar text: "
    Clustering: "Identify the topic or theme based on the text: "

# model:
#   _component_: sentence_transformers.SentenceTransformer
#   # https://huggingface.co/blevlabs/stella_en_v5
#   model_name_or_path: blevlabs/stella_en_v5
#   device: cuda
#   prompts:
#     ##
#     # task_name : "Prompt for the task"
#     # To be compatible with MTEB, task_name must be one of those 
#     # defined in mteb.abstasks.TaskMetadata.TASK_TYPE
#     ##
#     # s2s task
#     # Retrieval: "Instruct: Retrieve semantically similar text.\nQuery: "
#     # s2p task
#     Retrieval: "Instruct: Given a web search query, retrieve relevant passages that answer the query.\nQuery: "

# Eval arguments
eval:
  output_dir: /tmp/eval_output
  output_filename: eval_result_st__multilingual_e5_large.json 
  mteb:
    batch_size: 2048
    task_selectors: 
      - task_types: ["Retrieval"]
      - categories: []
      - languages: []

# Transform arguments
tokenizer:
  _component_: torchtune.models.llama3.llama3_tokenizer
  path: /tmp/Llama-3.2-1B-Instruct/original/tokenizer.model
  max_seq_len: 2048

# Device
dtype: bf16
seed: 1234
log_level: INFO
